-- IN LAB TAKS
-- TASK 1
CREATE TABLE EMPLOYEE(
emp_id INT PRIMARY KEY,
emp_name VARCHAR(50) NOT NULL,
salary DECIMAL(10,2) CONSTRAINT check_salary CHECK (salary>20000),
dept_id INT,
FOREIGN KEY (dept_id) REFERENCES DEPARTMENTS(department_id)
);

-- TASK 2

ALTER TABLE EMPLOYEE 
RENAME COLUMN emp_name TO full_name;

-- TASK 3
ALTER TABLE EMPLOYEE
DROP CONSTRAINT check_salary;

INSERT INTO EMPLOYEE (emp_id, full_name, salary, dept_id)
VALUES(1,'Rohan',15000,10);

-- TASK 4

CREATE TABLE DEPARTMENT(
dept_id INT PRIMARY KEY,
dept_name VARCHAR(15) UNIQUE
);
INSERT INTO DEPARTMENT(dept_id,dept_name)
VALUES(1,'ACADEMICS');

INSERT INTO DEPARTMENT(dept_id,dept_name)
VALUES(2,'MANAGEMENT');

INSERT INTO DEPARTMENT(dept_id,dept_name)
VALUES(3,'SALES');

-- TASK 5
ALTER TABLE employees
ADD CONSTRAINT fk_dept FOREIGN KEY (dept_id) REFERENCES departments(dept_id);

-- TASK 6
ALTER TABLE EMPLOYEE
ADD bonus NUMBER(6,2) DEFAULT 1000;

-- TASK 7
ALTER TABLE EMPLOYEE
ADD city VARCHAR2(20) DEFAULT 'Karachi';

ALTER TABLE EMPLOYEE
ADD age NUMBER CHECK (age > 18);

-- TASK 8
DELETE FROM EMPLOYEE WHERE emp_id IN (1,3);

-- TASK 9 
ALTER TABLE EMPLOYEE MODIFY (full_name VARCHAR2(20));
ALTER TABLE EMPLOYEE MODIFY (city VARCHAR2(20));

-- TASK 10
ALTER TABLE EMPLOYEE 
ADD email VARCHAR(50) UNIQUE;

-- POST LAB TASKS

